= Git
ifndef::imagesdir[:imagesdir: images]
ifndef::sourcedir[:sourcedir: ../../main/java]
:revealjs_theme: sky
:author: Greg Hutchinson
:url-wolpertinger: https://en.wikipedia.org/wiki/Wolpertinger
:checkedbox: pass:normal[{startsb}&#10004;{endsb}]
:title-slide-transition: zoom
:tip-caption: 💡


+++<small>+++
**D**istributed Version Control System
+++</small>+++

## Git Vs. Sharepoint
- Both are centralized locations for source documents
- Sharepoint only version controls individual files
- Sharing documents with people in the organization that do not have git already is tedious. Everyone has access to Sharepoint

## Git Vs. Sharepoint
- Git works locally and is really fast. Sharepoint is a little sluggish
- Git (in theory) takes an extra step or two to have the most current snapshot (pull, checkout)
- Git is more technical, steeper learning curve but because of this has a lot more features

[.columns]
## Centralized VCS - CVCS
[.column]
[graphviz, cvcs1, png]
----
digraph cvcs {
    size="70!"
    Repository [shape=cylinder, label="Central\nRepository" width=1];
    User1 [shape= rectangle, label="User1\nWorking\nCopy",];
    User2 [shape= rectangle, label="User2\nWorking\nCopy"];

    User1 -> Repository [label="commit"]
    Repository -> User1 [label="check-out"]
    User2 -> Repository [label="commit"]
    Repository -> User2 [label="check-out"]
}
----

[.column]
--
- Always had to be connected to the network 
- Committing changes - released changes (Can't commit in a partial state) 
- Checking-out your local copy possibly destroyed WIP
--

## Why Distributed VCS
- Central shared spot for documents
- Don't have to be connected to the network
- Versions are kept of the entire directory structures (not just individual files)
- Committing changes only affect the local repository. Commit freely and at any time
- Backups are implicit because of cloning
- All history is on the local computer


## DVCS 
[graphviz, dvcs1, png, width=800, height=500]
----
digraph dvcs {
    rankdir="BT"
    Repository [shape=cylinder, label="Central\nRepository" width=1 color=red];
    User1WC [shape= square, label="User1\nWorking\nCopy", style=filled; color=yellow];
    User2WC [shape= square, label="User2\nWorking\nCopy",style=filled; color=yellow]
    User1Rep [shape= cylinder, label="User1\nRepository", color=blue];
    User2Rep [shape= cylinder, label="User2\nRepository",color=blue];
    User1Rep -> Repository [label="push"]
    Repository -> User1Rep [label="pull"]
    User2Rep -> Repository [label="push"]
    Repository -> User2Rep [label="pull"]
    Repository -> User1Rep [label="clone"]
    Repository -> User2Rep [label="clone"]
    User1WC -> User1Rep [label="commit"]
    User1Rep -> User1WC [label="check-out"]
    User2WC -> User2Rep [label="commit"]
    User2Rep -> User2WC [label="check-out"]

    subgraph cluster_User1 {
        label="User1 Computer"
        User1Rep User1WC
    }
    subgraph cluster_User2 {
        label="User2 Computer"
        User2Rep User2WC
    }
}
----

## Terminology
- Remote Repository - The git repository that is hosted in the cloud or on another computer
- Local Repository - The git repository that is hosted on your local computer
- Working Copy - The current checked-out version to your local computer.
- Clone - Clone the *remote repository* and create the *local repository*

## Terminology
- Push - Push all deltas from the **local repository** to the **remote repository**
- Pull - Pull all deltas from the **remote repository** to the **local repository**
- Commit - Commit the changes in the **working copy** to the **local repository**
- Check-out - Replicated the **working copy** with an exact snapshot of this point in time from the **local repository**


[.columns]
## Scenario1 
[.column]
[graphviz, sc1-step1, png, width=700, height=500]
----
include::topics/sc1-step1.gv[]
----
[.column]
- User1 has cloned remote
- User2 has cloned remote
- User1 creates b.txt and commits
- User2 creates c.txt and commits

[.columns]
## Next 
[.column]
[graphviz, sc1-step2, png, width=700, height=500]
----
include::topics/sc1-step2.gv[]
----
[.column]
- User1 pushes changes
- User2's attempt to push changes will fail because of multiple remote heads

[.columns]
## Next 
[.column]
[graphviz, sc1-step3, png, width=800, height=500]
----
include::topics/sc1-step3.gv[]
----
[.column]
- User2 has pulled changes
- This has created 2 heads (locally)

[.columns]
## Next 
[.column]
[graphviz, sc1-step31, png, width=700, height=500]
----
include::topics/sc1-step31.gv[]
----
[.column]
- User2 has merged the 2 local heads into 1
- This can now be pushed


[.columns]
## Next 
[.column]
[graphviz, sc1-step4, png, width=700, height=500]
----
include::topics/sc1-step4.gv[]
----
[.column]
- User2 has pushed changes
- When User1 pulls, her graph will look identical again



